### ISSUE TITLE
Use dust parameters Av and Rv from GCR

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/sims_GCRCatSimInterface#9]
Per the discussion in #5 and https://github.com/LSSTDESC/gcr-catalogs/issues/70, the dust parameters Av and Rv will be included in the input catalog and become available in GCR, so this interface can (and should) directly use them.

I think this should be straightforward, basically revising (removing?) the function `get_internalDustParams` in [`python/desc/sims/GCRCatSimInterface/CatalogClasses.py`](https://github.com/LSSTDESC/sims_GCRCatSimInterface/blob/master/python/desc/sims/GCRCatSimInterface/CatalogClasses.py#L37).

@danielsf any thoughts? I think I can also help with this one.

**Comment by danielsf** [comment]
If we are now running the version of the GCR which include dust parameters, then: yes.  The catalog interface should be updated.  Note that the parameters will need to be mapped to `internalRv` and `internalAv`, which are the names of the parameters that PhoSim expects (as opposed to `galacticRv` and `galacticAv`, which characterize Milky Way dust).

**Comment by yymao** [comment]
I noticed that the current implementation allows the dust parameters (Av, Rv) having different values for disk and for bulge components. 

But the schema we have been using in GCR Catalogs assumes the dust parameters are the same for disk and for bulge (i.e., we have `A_v` but no `A_v_disk` nor `A_v_bulge`). And I think that's true for protoDC2 (@evevkovacs @dkorytov can you confirm?). 

So the question is, do we need `A_v_disk` and `A_v_bulge` (similar for `R_v`) in GCR Catalogs?

**Comment by evevkovacs** [comment]
@yymao Correct, there is no A_v_disk or A_v_bulge (although there could be, because the B and V filter luminosities are available for each component) @danielsf  should comment if these are ever likely to be needed.

**Comment by danielsf** [comment]
If there are different A_v and R_v for the disk and bulge, they will be used.  Since PhoSim treats a galaxy as two independent objects (a disk and a bulge) stacked on top of each other, PhoSim is capable of applying different dust extinction to both.

Whether or not the different parameter values are needed depends on what is realistic and how realistic we want to be.  I suspect that it is realistic to expect different dust properties in the disk and the bulge but, not being a galaxy expert, I'm to sure how significant the effect is.
